name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  ACR_NAME: acrroadmaprohith13 # <--- CHANGE THIS TO YOUR EXACT ACR NAME!
  IMAGE_NAME: iris-api

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 1. THE TASTE TESTER (CI)
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"
          cache: "pip"
          
      - name: Install dependencies
        run: pip install -r requirements.txt pytest httpx
        
      - name: Run Pytest
        run: python -m pytest -v

      # 2. UNLOCK THE WAREHOUSE
      - name: Login to Azure ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

       # ... (Login to Azure ACR step is here) ...

      # NEW MLOPS STEP: Bake a fresh AI Brain!
      - name: Train the ML Model
        run: python train.py

      # THE DELIVERY TRUCK (CD)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        # ... (rest of the code stays the same) ...

      # 3. THE DELIVERY TRUCK (CD)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Notice the tag! We are using the exact GitHub Commit ID (github.sha)
          tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}